apiVersion: v1
kind: Secret
metadata:
  name: additional-scrape-configs
  namespace: prometheus
type: Opaque
stringData:
  jenkins-scrape-config.yaml: |-
    - job_name: 'jenkins'
      metrics_path: /prometheus
      static_configs:
        - targets:
            - 'jenkins.jenkins.svc.cluster.local:8080'
