apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-alerts
  labels:
    {{- include "prometheus.server.labels" . | nindent 4 }}
data:
  {{- $files := .Files }}
  {{- range $path, $bytes := .Files.Glob "alert-rules/*.yaml" }}
  {{ base $path }}: |
    {{- $files.Get $path | nindent 4 }}
  {{- end }}
